### ISSUE TITLE
Angular ui-layout toggle not working

### ISSUE THREAD

**Issue by sooryailangovan** [angular-ui/ui-layout#177] opened 2016-01-13 05:06 UTC
Angular Version - 1.4.7 Ui-Layout Version - 1.4.1 Plunkr Link - http://plnkr.co/edit/S22WaqQRjtSNIPBYlHd7?p=preview

Collapse of section "two" in the plunkr example is not working using the toggle button in the one|two splitter. Likewise Collapse of section "four" in the plunkr example is not working using the toggle button in the three|four splitter. Please help

**Comment by SomeKittens** [comment] 2016-01-20 22:40
Dupe of #173

**Closed by SomeKittens** 2016-01-20 22:40 UTC
