### ISSUE TITLE
After resize rightmost container doesn't work on collapse/uncollaple

### ISSUE THREAD

**Issue by tommy-gansta** [angular-ui/ui-layout#174] opened 2016-01-06 11:30 UTC
Here is a link: [plnkr] (http://embed.plnkr.co/hPe5EVFamQWx1jdm0Q7j/). Steps to reproduce. Expand rightmost container, resize it, then collapse. The devider is still on the same place.

**Comment by SomeKittens** [comment] 2016-01-20 22:39
Dupe of #173

**Closed by SomeKittens** 2016-01-20 22:39 UTC
Labels: bug, PRs-please!
