### ISSUE TITLE
Square box with diamond appears on ui-splitbar

### ISSUE THREAD

**Issue by Farving** [angular-ui/ui-layout#118] opened 2015-08-28 20:56 UTC
When using bootstrap.css a small square box with a diamond inside is appearing on the ui-splitbar with class stretch. 

If I in the Chrome developer tools remove the stretch class, the square dissapears. And if I outcomment bootstrap, the square dissapears, however I cannot find any relation to what causes this square to appear.

**Comment by SomeKittens** [comment] 2015-08-28 21:51
Can you create a JSBin that reproduces this issue?

**Comment by Farving** [comment] 2015-08-31 07:33
https://jsbin.com/melowe/edit?html,css,js,output

As an addition, updated all libraries to latest version to check if it solves anything, which it doesn't. 
And by the way, it looks different in IE (haven't tried Opera or FireFox)

**Comment by SomeKittens** [comment] 2015-08-31 19:24
the up & down arrows are the toggle buttons for each UI-Layout container.  You don't typically see them because they're white on a white background.

**Comment by Farving** [comment] 2015-09-01 12:50
I'm quite aware of the up/down/left/right arrows function, but it's the additional square box as on this image:
http://s24.postimg.org/er0epa951/JSbin_snip.png

**Comment by SomeKittens** [comment] 2015-09-01 19:18
Reopening, that's an interesting problem.  I'm on Chrome, OSX, can't see it.  What OS are you on?  What does it look like with IE?


<img width="617" alt="screen shot 2015-09-01 at 12 17 21 pm" src="https://cloud.githubusercontent.com/assets/1616464/9613961/7c9b545e-50a3-11e5-989f-4f22c07589f6.png">

**Comment by Farving** [comment] 2015-09-02 06:13
![jsbin snip](https://cloud.githubusercontent.com/assets/1929580/9624158/28a95600-514a-11e5-83b7-8429f295d904.PNG)
I'm on Windows 7 and it's the same with Windows 8.1. My Chrome is Version 47.0.2497.0 canary and my Internet Explorer is version 11.something. And I think it's similar in Firefox.

**Comment by Farving** [comment] 2015-09-02 14:14
I've just testet it with Firefox on Windows and it doesn't seem to appear there.

**Comment by SomeKittens** [comment] 2015-09-02 16:46
Thanks for the update - I don't have Windows readily available but I'll see what I can do.

**Comment by Farving** [comment] 2015-09-02 19:36
Let me know if I can in any way assist you.

**Comment by SomeKittens** [comment] 2015-09-05 02:56
Fixed in 051b16408646b7bbd4710a83f0b4311e37f01a5a

(it was a scrollbar, by the way)

**Closed by SomeKittens** 2015-09-05 02:56 UTC
Labels: needs-repro
