### ISSUE TITLE
Splitbar is not collapse with the right column

### ISSUE THREAD

**Issue by proteye** [angular-ui/ui-layout#187] opened 2016-02-04 13:45 UTC
Hi.
I have a two draggable columns.
```
<div class="row">
  <div class="col-md-12">
    <div id="main-container" ui-layout="{flow : 'column'}" ui-layout-loaded>
      <div ui-layout-container><client-order-list></client-order-list></div>
      <div ui-layout-container>Right!</div>
    </div>
  </div>
</div>

```
The first application is loaded - that's ok. I click on splitbar arrows - columns and splitbar collapsed.
But, if I resize columns or click on the left splitbar arrow and then I click on the right arrow - right column collapsed (size = 0), but splitbar stays in place.

**Comment by SomeKittens** [comment] 2016-02-05 00:04
dupe of #173

**Closed by SomeKittens** 2016-02-05 00:04 UTC
