### ISSUE TITLE
Hide a panel then resize window bug

### ISSUE THREAD

**Issue by khaidev** [angular-ui/ui-layout#137] opened 2015-09-22 04:44 UTC
Toggle and resize window issue
1. Click toggle a panel to hide
2. Resize window
3. Panel hidden present (bug)
4. Click toggle a panel 
White panel present

![ui-layout-resize-window](https://cloud.githubusercontent.com/assets/5275043/10011025/8b2e5c06-611e-11e5-940b-f3bfc7511ba3.png)

**Comment by SomeKittens** [comment] 2015-09-24 03:17
This is a duplicate of #100 and #73

**Closed by SomeKittens** 2015-09-24 03:17 UTC
